# Generated by Django 3.0.3 on 2020-03-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='d_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='u_to',
            field=models.IntegerField(default=0),
        ),
    ]
